server:
  port: 9092
spring:
  application:
    name: gateway-server
  config:
    import: ${CONFIG_SERVER:configserver:http://localhost:9090}
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      retry:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
ribbon:
  ReadTimeout: 15000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7082/eureka/
      
      
management:
  endpoints:
    web:
      exposure:
        include: info
        
---
spring:
  config:
    activate:
      on-profile: default | dev-bs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/