server:
  port: ${PORT:7281}
spring:
  application:
    name: simple-cloud-gateway-filter
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      retry:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7282/eureka/