server:
  port: 9090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/madbarsoft-github/config-repository.git
          username: =============
          password: =============
          force-pull: true
eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info
