server:
  port: 8082
spring:
  application:
    name: microservice-two
  config:
    import: ${CONFIG_SERVER:configserver:http://localhost:9090}

management:
  endpoints:
    web:
      exposure:
        include: info

---
spring:
  config:
    activate:
      on-profile: default | dev-bs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/